### ISSUE TITLE
A note to say thank you, not an issue :) 

### ISSUE THREAD

**Issue by pzula** [drewish/planner#2]
Hey Drew!

Love your page generator! I created another fork for my A5 planner here: https://github.com/pzula/planner

Thank you for this brilliant script! This will make my timeblocked a LOT easier! I already use a small scale planner and hate to change to a different format. You really enabled me to get moving on timeblocking in the format I needed quickly. Thank you for sharing your work on Github!

**Comment by drewish** [comment]
Hey thanks for reaching out. I'm glad it's of use and that you were able to make it yours. I'll add a link to yours in the readme.

**Comment by drewish** [comment]
Added it in https://github.com/drewish/planner/commit/1f9a20a62ebce365d69eea9a95e2b741b1779e43
