### ISSUE TITLE
Generate a pdf for an entire year

### ISSUE THREAD

**Issue by jonny-wg2** [drewish/planner#4]
How could one generate a pdf with this template for an entire year?

**Comment by drewish** [comment]
i apologize for the delay in responding. hopefully we'll get this sorted before you need to generate your next year's file.

i used to have a constant for a number of weeks to print at a time but removed it at some point. i like the idea of this but think it might be best expressed as a second command line argument with a or number of weeks. then if you wanted to do a quarter at a time or a year you'd be able to. thoughts?

i'll spend some time on this next weekend.

**Comment by jonny-wg2** [comment]
Hi @drewish no problem at all.

Yeah I like your suggestion of adding some arguments where we could select the number of weeks, quarter, or a year.

I could see myself generating 4 pdfs, a per quarter basis, and send this to my remarkable for example. That would be great!

**Comment by drewish** [comment]
Give f1419b2e0e21cdb770622cf599d781da19c804ef a look. It should let you pass an option like `-w 4` or `--weeks 12` and do either 4 or 12 weeks at once.

**Comment by jonny-wg2** [comment]
Awesome looks good!
