### ISSUE TITLE
Add fixed appointments

### ISSUE THREAD

**Issue by Sumidu** [drewish/planner#6]
Dear drewish, 

I love your templates and have forked a forked of your fork and even added some internationalization. Now I've realized yours has many more options. So I will go back to yours. 

I really know only ChatGPTs/Copilots ruby support and am struggling to add fixed appointments in the time boxes. 

Is it possible to add something like the TASKS_BY_WDAY but for appointments?

So for example:

```
# Repeating Appointments by day of week, 0 is Sunday. Nested index is the hour.
APPOINTMENTS_BY_WDAY = [
  { nil },
  { 8 => 'Workout', 17 => 'Pick-Up Kids'},
  { 9 => 'Two hour workshop', 10 => 'Two hour workshop'},
  { 8 => 'Workout', 17 => 'Pick-Up Kids'},
  { 8 => 'Workout', 15 => 'Pick-Up Kids'},
  { 8 => 'Workout', 15 => 'Pick-Up Kids'},
  { 20 => 'Plan next week' },
]
```
I have no idea how to approach filling this in. So if you point me in the right direction, I am happy to take it from there.

**Comment by drewish** [comment]
Hey, glad you're finding it useful. It's a great request and something I'd been considering but hadn't found the time for it. I pushed it up so let me know how that works for you.
